spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: flyway

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.flyway.autoconfigure: DEBUG
