CREATE TABLE IF NOT EXISTS app_metadata (
    id UUID PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_metadata (id, key, value)
VALUES ('11111111-1111-1111-1111-111111111111', 'bootstrap.version', '0.1.0')
ON CONFLICT (key) DO NOTHING;
